candidate_peptides = ['QQSFVDCTCLK',
                      'RAGSAAVFWR',
                      'KPTLPVAAWEIR',
                      'LSHSPPSILKPVQSLSPR',
                      'VSPILSRPFIMQW',
                      'VPVTDESPATR',
                      'DAAQFTAQEK',
                      'ATGYPR',
                      'LSAYALPSSLSLR',
                      'RTWSAER',
                      'GEAKYFPFYSMR',
                      'RLLTAPVR',
                      'WDLEEEAENLIQEQSEDDQGWVWLPWSR',
                      'HVCGWRWLSWK',
                      'HAGAVR',
                      'LSEDFPQATGERPNR',
                      'LTGLEGEQLGIVSLR',
                      'VQTARPNR']
